openapi: 3.0.3
info:
  version: 1.0.0
  title: SHARK station.txt service
  description: Get content from the master list (station.txt)
tags:
- name: station
paths:
  /getfile:
    get:
      operationId: app.get_file
      tags:
      - station_file
      description: Return file content
      responses:
        200:
          description: Successful operation
          content:
            text/css:
              schema:
                type: string
        404:
          description: Not found
  /getdata:
    get:
      operationId: app.get_data
      tags:
      - get_station_data
      description: Return a json with station information
      parameters:
        - $ref: '#/components/parameters/attribute'
        - $ref: '#/components/parameters/attribute_list'
        - $ref: '#/components/parameters/all_attributes'
        - $ref: '#/components/parameters/local_id'
        - $ref: '#/components/parameters/station_localid'
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StationData'
        404:
          description: Something went down hill
components:
  schemas:
    FileContent:
      type: string
      example: REG_ID\tREG_ID_GROUP\tSTATION_NAME....
    StationData:
      type: object
      properties:
        REG_ID:
          type: string
          example: 135016
        REG_ID_GROUP:
          type: string
          example: 263603
        STATION_NAME:
          type: string
          example: N7 OST NIDINGEN
        SYNONYM_NAMES:
          type: string
          example: FLADEN1<or>FLADEN1(3)<or>KA 5
        ICES_STATION_NAME:
          type: string
          example: Nidingen
        LAT_DM:
          type: string
          example: 5718.20
        LONG_DM:
          type: string
          example: 1159.30
        LATITUDE_WGS84_SWEREF99_DD:
          type: string
          example: 57.3033
        LONGITUDE_WGS84_SWEREF99_DD:
          type: string
          example: 11.9883
        LATITUDE_SWEREF99TM:
          type: string
          example: 6355167
        LONGITUDE_SWEREF99TM:
          type: string
          example: 318574
        OUT_OF_BOUNDS_RADIUS:
          type: string
          example: 1200
        WADEP:
          type: string
          example: 26
        EU_CD:
          type: string
          example: SE635952-127000
        MEDIA:
          type: string
          example: Biota;Vatten
        COMNT:
          type: string
          example: VAL-2018-05-14
        OLD_SHARK_ID:
          type: string
          example: KANI52
  parameters:
    local_id:
      in: query
      name: local_id
      schema:
        type: string
        example: 135016
    station_localid:
      in: query
      name: station_localid
      schema:
        type: string
        example: 263603
    all_attributes:
      in: query
      name: all_attributes
      schema:
        type: boolean
        example: false
    attribute:
      in: query
      name: attribute
      schema:
        type: string
        example: STATION_NAME
    attribute_list:
      in: query
      name: attribute_list
      schema:
        type: string
        example: REG_ID,REG_ID_GROUP,STATION_NAME,SYNONYM_NAMES,ICES_STATION_NAME,LAT_DM,LONG_DM,LATITUDE_WGS84_SWEREF99_DD,LONGITUDE_WGS84_SWEREF99_DD,LATITUDE_SWEREF99TM,LONGITUDE_SWEREF99TM,OUT_OF_BOUNDS_RADIUS,WADEP,EU_CD,MEDIA,COMNT,OLD_SHARK_ID
